package web

import (
	"strconv"
	"strings"
	"unicode"
)

// modelToolProgress returns only an explicit status line authored by the
// upstream model. The gateway does not fabricate progress text.
func modelToolProgress(text string) string {
	return sanitizePublicAssistantText(strings.TrimSpace(toolDecisionStatus(text)))
}

func containsHan(text string) bool {
	for _, r := range text {
		if unicode.Is(unicode.Han, r) {
			return true
		}
	}
	return false
}

// toolProgressText is kept for callers that do not have a conversation ledger.
// The request path uses toolProgressTextForStage so a continuation does not
// repeat the first-turn preamble in every tool round.
func toolProgressText(prompt string, calls []detectedToolCall) string {
	return toolProgressTextForStage(prompt, calls, 0)
}

// toolProgressTextForStage is a public, non-reasoning status line. It is
// generated by the gateway only to bridge the small gap before a tool event;
// it must describe the actual next action and change after a tool result is
// received. The completed count is the active-turn stage, not a global count.
func toolProgressTextForStage(prompt string, calls []detectedToolCall, completed int) string {
	if completed < 0 {
		completed = 0
	}
	zh := containsHan(prompt)
	action := toolProgressAction(calls, zh)
	step := completed + 1
	if zh {
		if completed == 0 {
			return "我先处理第 1 步：" + action + "。"
		}
		return "上一步结果已返回，我继续处理第 " + strconv.Itoa(step) + " 步：" + action + "。"
	}
	if completed == 0 {
		return "I’ll handle step 1: " + action + "."
	}
	return "The previous result is back; I’ll continue with step " + strconv.Itoa(step) + ": " + action + "."
}

func toolProgressAction(calls []detectedToolCall, zh bool) string {
	name := ""
	if len(calls) > 0 {
		name = strings.ToLower(strings.TrimSpace(calls[0].Name))
	}
	switch name {
	case "exec", "shell_command", "terminal", "run_command":
		if !zh {
			return "check the environment and run the request"
		}
		return "检查环境并执行请求"
	case "apply_patch", "write_file", "edit_file":
		if !zh {
			return "verify the target files and apply the change"
		}
		return "核对目标文件并应用修改"
	case "view_image", "open_image":
		if !zh {
			return "read the image and verify the important details"
		}
		return "读取图片并核对关键细节"
	case "browser", "browser_open", "navigate", "computer_use":
		if !zh {
			return "open the page and verify its current state"
		}
		return "打开页面并核对当前状态"
	case "search", "web_search", "search_web":
		if !zh {
			return "search the relevant sources and verify the result"
		}
		return "检索相关资料并核对结果"
	default:
		if zh || containsHan(name) {
			return "执行请求并核对结果"
		}
		return "run the requested action and verify the result"
	}
}

func toolProgressContinuation(prompt string) string {
	if containsHan(prompt) {
		return "处理路径已经确定，我继续执行并核对结果。"
	}
	return "The next step is clear; I’ll run it and verify the result."
}
